# Generated by Django 2.2.12 on 2022-11-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsystem_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
