name: Run Django Tests
on:
  - push
  - pull_request

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        run: pip install django django-crispy-forms
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          cd ${{github.workspace}}/src/foodsystem
          python manage.py test foodsystem
